#*************************************************************************** #
#                                                                            #
#                                                        :::      ::::::::   #
#   ft_list_clear.c                                    :+:      :+:    :+:   #
#                                                    +:+ +:+         +:+     #
#   By: schapuis <marvin@42.fr>                    +#+  +:+       +#+        #
#                                                +#+#+#+#+#+   +#+           #
#   Created: 2013/08/28 14:57:59 by schapuis          #+#    #+#             #
#   Updated: 2013/08/28 15:11:33 by schapuis         ###   ########.fr       #
#                                                                            #
# ************************************************************************** #

NAME = do-op
SRCS = do-op.c
CC = gcc
CFLAGS = -Wall -Wextra -Werror -o
RM = rm -f

all:
	${CC} ${CFLAGS} ${NAME} ${SRCS}

clean:
	${RM} a.out
